### ISSUE TITLE
problem: content area doesn't allow scroll

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#1]
Problem: the area where main content is displayed cannot be scrolled.

Solution: fix the tailwind style

<img width="1441" alt="Screenshot 2024-07-03 at 9 09 08 PM" src="https://github.com/nostrocket/hypergolic/assets/8143945/ce03368c-363d-4dba-bac7-ef12f0ea0c62">

Slot location:
https://github.com/nostrocket/hypergolic/blob/c9ea5b28c911258662788ebc21a6f3909ef707c1/src/layouts/SidePanelLayout.svelte#L107

**Comment by bob2402** [comment]
I will work on this issue.
