### ISSUE TITLE
Problem: can't see info about contributors

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#118]
There are contributors listed in the Merits and Satflow table, but you can't go and view their profile so it's not clear who they are etc.

Solution:
Add a hover card (https://www.shadcn-svelte.com/docs/components/hover-card) that shows the user's profile info (whatever is easy to get from NDK I guess?) and add a link to open the profile in some of the nostr clients like primal/nostrudel/coracle

**Comment by bob2402** [comment]
I will work on this problem.
