### ISSUE TITLE
problem: can't create real rockets

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#124]
Users can only create testnet rockets, and if I enable the creation of mainnet rockets people create spammy testnet rockets but put them on mainnet.

## Solution:

Charge a fee for the creation of mainnet rockets.

1. When users go to create a rocket, add a checkbox to make it a real/mainnet rocket. If this box is checked, show them some text explaining that they need to pay 10k sats (or whatever), and update the text on the publish button to say 'pay 10k sats'. Generate an invoice (same as paying for a product). The main difference between this and paying for a product is that product payments zap whatever rocket the product belongs to, but this one should only zap the nostrocket rocket.

2. The zap request (kind 5734) must also include the name that the user has entered (the name of the rocket), this should be done using a tag. `["name", <string>]`. We already do something similar when zapping to pay for products, so check that.

3. Publish a 31108 event to create the new rocket (as normal).

4. Once there's a PR for this, I will log a new problem explaining how to handle the zap receipt (kind 5735) and update the nostrocket rocket state to add the newly created rocket name.

**Comment by bob2402** [comment]
I will work on this problem.
