### ISSUE TITLE
Problem: new users can't experiment with a new pubkey

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#128]
Solution:
Add an extra popup card thing that displays when the user clicks sign in. 

On this popup, give users 3 options:
Login with a extension, login with bunker, and "use temporary account" button which logs in with a newly generated key.

Show the user the new nsec so they can save it if they want.

**Comment by bob2402** [comment]
I will work on this problem.

**Comment by bob2402** [comment]
After creating a temporary account, is it still necessary to give a "login by private key"?

**Comment by gsovereignty** [comment]
> After creating a temporary account, is it still necessary to give a "login by private key"?


Actually, another problem is that users cannot log out once they are logged in. Maybe just do that.

**Comment by bob2402** [comment]
> > After creating a temporary account, is it still necessary to give a "login by private key"?
> 
> Actually, another problem is that users cannot log out once they are logged in. Maybe just do that.

To facilitate debugging, the log out method has been implemented and will be released together in the subsequent PR.
