### ISSUE TITLE
problem: Products and Purchases element layout is bad

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#13]
`/rockets/[ignition]`

<img width="1145" alt="Screenshot 2024-07-12 at 8 41 47 PM" src="https://github.com/user-attachments/assets/4112c866-2995-4797-bc82-5c7165d5da75">

The purchases shown are for the specific product shown, but it looks like they are kind of unrelated.

solution: make a better layout for displaying the purchases of a product. 
Keep in mind that:
- there can be more than one product for each rocket
- The product display card also needs to be used elsewhere (e.g. `/products`)

**Comment by bob2402** [comment]
I will work on this problem.
