### ISSUE TITLE
problem: I'm forced to select every checkbox when approving a merit request

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#130]
<img width="766" alt="Screenshot 2024-08-31 at 11 22 49 AM" src="https://github.com/user-attachments/assets/acc7e106-12ad-4842-8c17-072bdc944824">

This list is necessary to remind us what we should be looking for when approving/rejecting a merit request, but when dealing with a large number of merit requests it becomes very time consuming.

Solution:
Add one more checkbox at the end of the list "select all" which selects all of the items at once.

**Comment by bob2402** [comment]
I will work on this problem.
