### ISSUE TITLE
problem: not sure why signatures are missing when using NDKCacheAdapter

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#16]
`ndk.ts`

When `ndk.cacheAdapter` is set, whenever we query an event received from a relay, the signature of the event is missing.

To test, simply console.log some events and look for the signature, also check `event.rawEvent()` to get the underlying NostrTools event.

I'm not sure if this is something to do with hypergolic, or if it's something to do with NDK.

Solution: I guess the first step is to create a new boilerplate svelte project with NDK and test if it has the same behaviour.

**Comment by bob2402** [comment]
I will work on this problem.

**Comment by bob2402** [comment]
the boilerplate: https://github.com/bob2402/reproduce-lost-signature

There is not only one scenario of losing signature, I have currently tried to reproduce this one. It can be confirmed that it is related to NDKCacheAdapterDexie.

**Comment by gsovereignty** [comment]
Closing as this is a problem with the upstream library
