### ISSUE TITLE
problem: value in USD not displayed

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#17]
`/rockets/merits/[id]`

We are not displaying the reference amount in USD.

It will also be required in other places later.

Should be able to mostly just copy this from https://github.com/nostrocket/oxygen/blob/ad33621948853fda0c0a6eb46b32791f675cce74/src/components/elements/CuckLoserBucks.svelte#L15

Location: $10,000 in this screenshot:
<img width="790" alt="Screenshot 2024-07-16 at 5 15 46 PM" src="https://github.com/user-attachments/assets/dd3fed47-94b4-48e3-aad1-6812e1a8d9cf">

**Comment by bob2402** [comment]
I will work on this problem.
