### ISSUE TITLE
problem: `/` route doesn't look as good as it could

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#19]
The landing route `/` doesn't look as good as it could.

Solution: make the card components flow more nicely.

**Comment by bob2402** [comment]
Can you describe in more detail?

**Comment by gsovereignty** [comment]
> Can you describe in more detail?

For example, the cards are all different heights, which makes it look weird, but I'm not sure what to do about this because the text length on these types of things is never going to be exactly the same. I might ask a UX designer to provide some suggestions first, so just ignore this one for now.
