### ISSUE TITLE
problem: `d` tag is not validated

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#24]
This field is not validated.

<img width="436" alt="Screenshot 2024-07-18 at 1 33 40 PM" src="https://github.com/user-attachments/assets/a481c28b-e065-4c37-abd0-b4150cdf5635">

Solution: validate that it is a valid `d` tag using regex (this is implemented in Oxygen already, so check Oxygen repo for the rocket name regex).

Report error to user (maybe make the form border red or something when error), display error underneath the form.

https://www.shadcn-svelte.com/docs/components/form

**Comment by bob2402** [comment]
I will work on this problem.
