### ISSUE TITLE
problem: can't see if merit request is approved/rejected/pending

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#28]
`/rockets`

It's not clear if a merit request is approved/rejected or still waiting for votes unless we actually go into the merit dashboard page.

<img width="1128" alt="Screenshot 2024-07-22 at 3 45 00 PM" src="https://github.com/user-attachments/assets/37a4b577-0a98-45fb-8bc0-03919f99a06b">

Solution: make the background of the table dependent on the status of the merit request. The code for checking merit request status can be seen on the merit dashboard `/rockets/merits/[id]`

**Comment by bob2402** [comment]
I will work on this problem.
