### ISSUE TITLE
problem: buying products doesn't work without WebLN

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#29]
Some users might not have a WebLN enabled extension for making payments, so they need a QR code that they can scan instead.

Also right now the payment is only triggered by clicking `test` in the UI. This should be a button instead.

Solution:

Implement "pay xx sats now" button. Display a QR code for the invoice, also allow user to copy the invoice string, or click "use browser extension" if webLN is detected.

**Comment by bob2402** [comment]
I will work on this problem.
