### ISSUE TITLE
Problem: it's not easy for users to figure out how many Merits they should request

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#32]
When users are creating a new merit request, it just asks them for an amount of merits (denominated in sats).

It's not clear to them how much they should request. 

Solution: 

Add a "help" button next to this field on the form, and open up another dialogue to help them calculate the number of sats. 

The dialogue should ask them:
Their hourly rate in USD,
How many minutes they spent solving the problem.

This can then be used to calculate the number of sats based on the current Bitcoin price, and when they click OK inject it into the merit request form.

**Comment by bob2402** [comment]
I will work on this problem.
