### ISSUE TITLE
Problem: merit requests that are only a github are annyoing

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#34]
When submitting a merit request, it's acceptable to paste in a link to a github issue.

The problem is that seeing just a link to the issue doesn't let is quickly see what the problem is.

Solution:

When rendering the problem statement, if it's a github link (and no other content), attempt to fetch the heading of the issue from the github API (can we do this without using an API key?)

<img width="1111" alt="Screenshot 2024-07-22 at 4 42 38 PM" src="https://github.com/user-attachments/assets/e46e069b-db10-41cf-855d-150837c8049e">
<img width="764" alt="Screenshot 2024-07-22 at 4 42 11 PM" src="https://github.com/user-attachments/assets/cdf1ed3f-4379-4c38-9bdf-7c5d56df5278">

**Comment by bob2402** [comment]
Maybe we can get the html title.

```bash
curl -L https://github.com/nostrocket/hypergolic/issues/34 | sed -n 's/.*<title>\(.*\)<\/title>.*/\1/ip'
```

**Comment by gsovereignty** [comment]
> Maybe we can get the html title.
> 
> ```shell
> curl -L https://github.com/nostrocket/hypergolic/issues/34 | sed -n 's/.*<title>\(.*\)<\/title>.*/\1/ip'
> ```

Yeah that's probably the simplest way to do it as long as there are no CORS errors.

**Comment by bob2402** [comment]
I found an API that can retrieve GitHub issue information.
```
https://api.github.com/repos/nostrocket/hypergolic/issues/34
```
