### ISSUE TITLE
problem: can't see who created a Rocket

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#4]
at `/rockets` we can't see who created a rocket

code reference: https://github.com/nostrocket/hypergolic/blob/MASTER/src/components/RocketCard.svelte

solution: fetch the event author's profile data and render it in a nice way on the rocket card.

Have a look at https://github.com/pablof7z/highlighter and https://github.com/pablof7z/wiki/ to see how to do this with NDK.

**Comment by bob2402** [comment]
I will work on this problem.

**Comment by gsovereignty** [comment]
@bob2402 also have a look at https://github.com/nostrocket/humble.horse/blob/master/src/lib/components/UserProfilePic.svelte and https://github.com/nostrocket/humble.horse/blob/master/src/lib/components/UserDisplayName.svelte for reference
