### ISSUE TITLE
problem: can't see who's currently logged in

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#5]
At the top-right there is a profile menu but we can't see who is currently logged in.

Solution: fetch current user's profile and render in a nice way.

If no one is logged in, just show the sign in button (feel free to modify and consolidate this menu and button)

code references: https://github.com/nostrocket/hypergolic/blob/f770fc04b7ae29bd28533b8575a5f307a26bcb55/src/layouts/SidePanelLayout.svelte#L92

https://github.com/nostrocket/hypergolic/blob/MASTER/src/components/Login.svelte

**Comment by bob2402** [comment]
I will work on this problem.
