### ISSUE TITLE
problem: users can't provide email address or npub for notifications

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#55]
Nostrocket isn't really ready for most people yet.

We should let them provide an npub or email address to be told when there are new updates.

solution:

`NotifyMe.svelte`
If user is logged in, give them a button: "Tell me via DM when there are updates", send a DM to me onclick with something like "please give me nostrocket updates".

If users is not logged in, show the login button, but also allow them to enter an email address.

If user enters an email address, generate a new random key and send me a DM containing their email address.

**Comment by bob2402** [comment]
I will work on this problem.
