### ISSUE TITLE
problem: can't add or modify the mission tag for a rocket

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#6]
From `/` go to "create new rocket".

The page after redirect is here: https://github.com/nostrocket/hypergolic/blob/f770fc04b7ae29bd28533b8575a5f307a26bcb55/src/routes/rockets/%5Bignition%5D/%2Bpage.svelte#L55

The mission tag `["mission" <mission statement, less than 140 chars>]` (see https://github.com/nostrocket/NIPS/blob/main/MSBR334000.md) cannot be modified.

Note that to modify the mission tag we must also comply with https://github.com/nostrocket/NIPS/blob/main/31108.md when publishing the new 31108 replaceable event.

The important part is to include the `parent` (which is the current event being viewed) and the `ignition` tag (if the current event being viewed does not have an ignition tag then it **is** the ignition event so we use this id as the ignition tag).

**Comment by bob2402** [comment]
I will work on this problem.

**Comment by gsovereignty** [comment]
@bob2402 for reference: https://github.com/nostrocket/hypergolic/blob/MASTER/src/components/AddProductToRocket.svelte

**Comment by gsovereignty** [comment]
@bob2402 it's safe to work on this now, the best way to solve this is add it to the class in rocket.ts, make a new dialogue for UI, and wire it into the rocket dashboard.

Also don't forget to check if the current user has votepower within the rocket (look at the way that voting on merit requests does this)

**Comment by bob2402** [comment]
I will work on this problem.
