### ISSUE TITLE
problem: wrong profile sometimes displayed on `/buymerits`

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#60]
<img width="1133" alt="Screenshot 2024-08-05 at 1 46 14 PM" src="https://github.com/user-attachments/assets/3ec55fd0-14d8-40ac-8afa-bc620025f88e">

The merit sale at the top is created by Bob, but sometimes it shows my profile pic instead.

**Comment by bob2402** [comment]
I will work on this problem.
