### ISSUE TITLE
problem: merits and satflow graph/table has a limited number of colors

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#64]
The merits/satflow table has a limited number of colors that can be used, but we will soon have new contributors and will run out of colors to show.

Solution: add some more colours that can be used. Choose colors that are different enough so that if they are side by side on the graph you can still easily see that they are different people.

I think for now, 10 colors in total should be enough

**Comment by bob2402** [comment]
I will work on this problem.
