### ISSUE TITLE
Problem: not clear which rockets are for testing, and which are real

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#65]
We will have real users soon, but it's not clear which rockets are real and which rockets are testing.

Solution: detect `test` in the name of the rocket and add a badge or icon next to its name, with a popup or something to explain that any rocket with "test" in its name is a rocket for testing and not real.

In addition to this: 
1. on the `/rockets` route use a tab to display `mainnet` and `testnet` rockets (https://www.shadcn-svelte.com/docs/components/tabs)

2. For the buy/sell merits routes there should be a warning not to send real Bitcoin because it's just a testing rocket.

**Comment by bob2402** [comment]
Due to the coupling between this problem and the solution of #66, it needs to attempt to solve it after the merger at #73.
