### ISSUE TITLE
problem: merits and satflow graph doesn't highlight on hover

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#76]
When you hover over the graph it highlights the graph, but when you over over someone on the merits/revenue table, it doesn't highlight the graph.

<img width="1141" alt="Screenshot 2024-08-09 at 1 08 50 PM" src="https://github.com/user-attachments/assets/1d597138-bca6-4278-80d4-d3fc2b36639b">

**Comment by bob2402** [comment]
I will work on this problem.

**Comment by bob2402** [comment]
I will work on this problem.
