### ISSUE TITLE
problem: it's not obvious when the amount of sats paid to merit holders is increased

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#84]
For the live demo in Riga I want it to be really obvious when someone pays for a product.

The best way to show this is probably to use [svelte motion](https://svelte.dev/docs/svelte-motion) when increasing the Sats in the merits and satflow component.

Maybe also expand the size of the text for the numbers during the motion transition to make it really obvious, but only if it's not complicated to implement (got a feeling it might be)

**Comment by bob2402** [comment]
There is an problem: after a user purchases a product, the merits in the Merits and Satflow component do not increase.

**Comment by gsovereignty** [comment]
The merits are not supposed to increase when someone pays, only the Revenue (sats) increases.

**Comment by samuelralak** [comment]
picking this
