### ISSUE TITLE
problem: not clear when someone makes a purchase

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#94]
solution:

Create a popup thing that covers the merits/satflow pie chart whenever someone makes a purchase. Perhaps this component: https://www.shadcn-svelte.com/docs/components/sonner

Show the buyer's avatar and name.

Display for like 2 seconds and then disappear

This can be accomplished by hooking into the unratifiedZaps object and displaying the component for each zap. To prevent displaying all the zaps every time the page opens, only display with the zap event `created_at` is in the last few seconds.

**Comment by bob2402** [comment]
I will work on this problem.
