### ISSUE TITLE
problem: the list of purchases is sometimes very long

### ISSUE THREAD

**Issue by gsovereignty** [nostrocket/hypergolic#95]
<img width="867" alt="Screenshot 2024-08-17 at 6 01 00 PM" src="https://github.com/user-attachments/assets/120f0b62-8373-4ff1-a31d-f22f5ca2a3ea">

Solution: only display the latest 5 purchases, and add a button to expand the list and show all.

For reference, this has already been implemented for the Merit Request table.

**Comment by bob2402** [comment]
I will work on this problem.
